### ISSUE TITLE
[Login] Unable to login using Riot Games (blank page)

### ISSUE THREAD

**Issue by Hurdenn** [RumbleMike/Assist#1]
**Environment:**
OS: Windows 10 64
Chip: Intel i5-4450 
GC: GTX 750
Location: France

**Steps to reproduce:**
1. Start Assist
2. Click 'Login with Riot Games'
3. Click 'Login'

**Expected result:**
The Riot Games account login page shows up in the new window

**Actual result**
A new window opens, the content is blank.

![image](https://user-images.githubusercontent.com/83715128/152662364-23cbc6aa-71e4-4072-991a-85a33ec3528a.png)

*Well done for the project Mike, gl*

**Comment by RumbleMike** [comment]
Thanks for the issue, Currently I am looking into it. A Patch is out as a temporary fix to remove Riot Login and just use Username/Password.

I Know many users prefer the Riot Login, I am looking into this issue. Thanks for the Report.

**Comment by RumbleMike** [comment]
Should be fixed with v1.0.3

Let me know if this is fixed. So i can close this.
