### ISSUE TITLE
When i download it, windows detect as a Virus

### ISSUE THREAD

**Issue by WalMCA** [RumbleMike/Assist#11]
When i try to Download or Open the Setup or the .Exe from the Zip, always says that is a virus, and will damage my computer, and when i go to VirusTotal.com submit the Setup or the Exe, it says that is also a Virus, what really in this app?
![image](https://user-images.githubusercontent.com/99229848/152905279-d0af53c3-d976-48ec-a469-69a33dd32e97.png)
![image](https://user-images.githubusercontent.com/99229848/152905313-b2059d4d-696d-46be-93ba-9e7ccae013be.png)

**Comment by RumbleMike** [comment]
False Positive, Sadly i have submitted a request to Microsoft and they have removed it but i cannot contact the other parties in virus total. You can go through the source and see if you are worried.

**Comment by WalMCA** [comment]
> False Positive, Sadly i have submitted a request to Microsoft and they have removed it but i cannot contact the other parties in virus total. You can go through the source and see if you are worried.

I did every single type of Search and Virus detect, and i saw nothing problematic, no problem man, sorry for this, i was only kinda Scared lol, thx and congrats for the App, it's amazing
