### ISSUE TITLE
Crash when switching accounts

### ISSUE THREAD

**Issue by Simber1** [RumbleMike/Assist#14]
I got this crash when switching accounts today. Not quite sure what triggered it, Assist had been open for a few hours. Next time I switched account it was fine

![image](https://user-images.githubusercontent.com/16944153/153713561-99eb1af9-8fa4-49b0-a484-4a2ea8bede04.png)

**Comment by Simber1** [comment]
I think this is vaguely reproduced by clicking on the account you want to switch to multiple times in quick succession

**Comment by RumbleMike** [comment]
Possibly Fixed in latest update, please let me know so i can close this ticket.

**Comment by Simber1** [comment]
Doesn't seem to crash anymore but it still causes an expired auth popup pretty consistently
