### ISSUE TITLE
Sidebar flicker when hovering too quickly

### ISSUE THREAD

**Issue by selbstmord** [RumbleMike/Assist#16]
OS: Win 11
Media: 
https://i.imgur.com/1wIPDbc.gif
https://i.imgur.com/XATpUtz.gif 
Seems like an issue with the smooth open / close effect bugging out. It actually flickers way harder but that's not visible due to the low framerate.

**Comment by rahulbhatt1899** [comment]
Hey, could you assign this issue to me?
I would like to contribute to this repository.

**Comment by RumbleMike** [comment]
This will be fixed in a future version!
